"""
notifier.py — Sends the Groq-generated digest via Gmail (SMTP + App Password).

Uses Python's built-in smtplib so no external email library is required.
The digest is sent as a styled HTML email with a plain-text fallback.
Each of the 4 categories gets a distinct subject line and header colour.
"""

import logging
import smtplib
from datetime import datetime, timezone, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)

IST = timezone(timedelta(hours=5, minutes=30))

# ---------------------------------------------------------------------------
# Email HTML Wrapper
# ---------------------------------------------------------------------------

_HTML_SHELL = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Stock Research Digest</title>
  <style>
    /* ---- Reset ---- */
    body, p, h1, h2, h3, h4, ul, ol, li {{
      margin: 0; padding: 0;
    }}

    /* ---- Layout ---- */
    body {{
      background-color: #f0f2f5;
      font-family: 'Segoe UI', Arial, Helvetica, sans-serif;
      font-size: 15px;
      color: #1a1a2e;
      padding: 24px 12px;
    }}
    .wrapper {{
      max-width: 680px;
      margin: 0 auto;
    }}

    /* ---- Header Banner ---- */
    .header {{
      background: linear-gradient(135deg, #0f3460 0%, #16213e 100%);
      border-radius: 12px 12px 0 0;
      padding: 28px 32px;
      color: white;
      text-align: center;
    }}
    .header h1 {{
      font-size: 22px;
      letter-spacing: 0.5px;
      margin-bottom: 6px;
    }}
    .header p {{
      font-size: 13px;
      color: #a0aec0;
    }}

    /* ---- Body Card ---- */
    .card {{
      background: #ffffff;
      padding: 28px 32px;
      border-left: 1px solid #e2e8f0;
      border-right: 1px solid #e2e8f0;
    }}

    /* ---- Typography ---- */
    h2 {{
      font-size: 18px;
      color: #0f3460;
      margin: 28px 0 8px;
      border-bottom: 2px solid #e94560;
      padding-bottom: 6px;
    }}
    h3 {{
      font-size: 16px;
      color: #16213e;
      margin: 22px 0 8px;
    }}
    p {{
      line-height: 1.7;
      margin-bottom: 12px;
      color: #2d3748;
    }}
    ul, ol {{
      padding-left: 20px;
      margin-bottom: 14px;
    }}
    li {{
      margin-bottom: 8px;
      line-height: 1.6;
    }}
    hr {{
      border: none;
      border-top: 1px solid #e2e8f0;
      margin: 18px 0;
    }}
    b, strong {{
      color: #1a1a2e;
    }}

    /* ---- Footer ---- */
    .footer {{
      background: #f7fafc;
      border: 1px solid #e2e8f0;
      border-radius: 0 0 12px 12px;
      padding: 18px 32px;
      text-align: center;
      font-size: 12px;
      color: #718096;
    }}
    .footer a {{
      color: #0f3460;
      text-decoration: none;
    }}

    /* ---- Stats Bar ---- */
    .stats {{
      display: flex;
      gap: 16px;
      background: #f7fafc;
      border-radius: 8px;
      padding: 14px 18px;
      margin: 16px 0;
      border: 1px solid #e2e8f0;
      flex-wrap: wrap;
    }}
    .stat-item {{
      flex: 1;
      min-width: 100px;
      text-align: center;
    }}
    .stat-item .num {{
      font-size: 20px;
      font-weight: 700;
      color: #0f3460;
    }}
    .stat-item .label {{
      font-size: 11px;
      color: #718096;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }}
  </style>
</head>
<body>
<div class="wrapper">

  <!-- Header -->
  <div class="header" style="background: linear-gradient(135deg, {header_color} 0%, #16213e 100%);">
    <h1>{category_label} Digest</h1>
    <p>{date_str} &nbsp;|&nbsp; Powered by Groq AI</p>
  </div>

  <!-- Stats Bar -->
  <div class="card">
    <div class="stats">
      <div class="stat-item">
        <div class="num">{num_handles}</div>
        <div class="label">Researchers</div>
      </div>
      <div class="stat-item">
        <div class="num">{num_posts}</div>
        <div class="label">Posts Analysed</div>
      </div>
      <div class="stat-item">
        <div class="num">{hours}h</div>
        <div class="label">Lookback</div>
      </div>
      <div class="stat-item">
        <div class="num">{gen_time}</div>
        <div class="label">Generated at (IST)</div>
      </div>
    </div>
  </div>

  <!-- Digest Content -->
  <div class="card">
    {digest_html}
  </div>

  <!-- Footer -->
  <div class="footer">
    <p>
      This digest was auto-generated by <b>Stock Research Aggregator</b> using Groq AI (Llama 3.3).<br>
      Sources: Public posts from tracked X (Twitter) handles via Nitter RSS.<br>
      <b>Not SEBI-registered investment advice. Do your own research.</b>
    </p>
  </div>

</div>
</body>
</html>
"""

_PLAIN_TEXT_FALLBACK = """\
Stock Research Digest — {date_str}
Researchers: {num_handles} | Posts: {num_posts} | Lookback: {hours}h

[This email requires an HTML-capable email client to view properly.]

Please open this email in Gmail or another modern email client.
"""


# ---------------------------------------------------------------------------
# Send Email
# ---------------------------------------------------------------------------

def send_digest(
    digest_html: str,
    sender_email: str,
    app_password: str,
    recipient_email: str,
    num_handles: int,
    num_posts: int,
    lookback_hours: int = 24,
    category: str = "analysis",
    category_label: str = "📊 Analysis",
    category_color: str = "#0f3460",
) -> None:
    """
    Send the HTML digest email via Gmail SMTP using an App Password.

    Args:
        digest_html:      The Groq-generated HTML content.
        sender_email:     Your Gmail address.
        app_password:     Gmail App Password (16-char, spaces allowed).
        recipient_email:  Delivery address.
        num_handles:      Number of handles tracked (for stats bar).
        num_posts:        Number of posts analysed (for stats bar).
        lookback_hours:   Lookback window (for stats bar).
        category:         Category ID (for logging).
        category_label:   Human-readable label from config (e.g., '📊 Analysis').
        category_color:   Hex colour from config (e.g., '#0f3460').
    """
    now_ist = datetime.now(IST)
    date_str = now_ist.strftime("%d %B %Y")
    gen_time = now_ist.strftime("%H:%M")
    subject = f"{category_label} Digest — {date_str}"
    header_color = category_color

    # Build full HTML
    full_html = _HTML_SHELL.format(
        date_str=date_str,
        num_handles=num_handles,
        num_posts=num_posts,
        hours=lookback_hours,
        gen_time=gen_time,
        digest_html=digest_html,
        category_label=category_label,
        header_color=header_color,
    )

    plain_text = _PLAIN_TEXT_FALLBACK.format(
        date_str=date_str,
        num_handles=num_handles,
        num_posts=num_posts,
        hours=lookback_hours,
    )

    # Assemble MIME message
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"Stock Research Digest <{sender_email}>"
    msg["To"] = recipient_email

    # Attach plain text first (fallback), then HTML (preferred)
    msg.attach(MIMEText(plain_text, "plain", "utf-8"))
    msg.attach(MIMEText(full_html, "html", "utf-8"))

    logger.info(f"Sending digest to {recipient_email} …")

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(sender_email, app_password.replace(" ", ""))
            server.sendmail(sender_email, recipient_email, msg.as_string())

        logger.info(f"✓ Email sent successfully → {recipient_email}")

    except smtplib.SMTPAuthenticationError:
        logger.error(
            "Gmail authentication failed. "
            "Make sure you are using an App Password (not your Gmail login password). "
            "See README.md for setup instructions."
        )
        raise
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        raise
